version: "3.8"
services:
  # development mode
  # storage in memory
  vault:
    image: vault
    container_name: mw_vault
    ports:
      - 8200:8200
    restart: always
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
#      - VAULT_ADDR="https://kolegran-vault.herokuapp.com"
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=root
    cap_add:
      - IPC_LOCK