version: '3.9'
services:
  mw-pg:
    image: postgres:10
    environment:
      POSTGRES_DB: mwdev
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - /data:/var/lib/postgresql/data
    ports:
      - 5432:5432