version: '3.9'
services:
  mw-pg:
    image: postgres:10
    environment:
      POSTGRES_DB: mwdev
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5435:5432